version: '3.5'

services:
  postgres:
    container_name: "blog.postgres"
    image: postgres:15-alpine
    restart: unless-stopped

    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1234}
      - POSTGRES_DB=${POSTGRES_DB:-blog}

    ports:
      - "127.0.0.1:1488:5432"
    volumes:
      - /Users/ilasapovalov/Desktop/blog-data:/var/lib/postgresql/data

